org: eslamserverless
app: providers-test
service: providers-test
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
# test 2
functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
